# Generated by Django 3.0.7 on 2020-06-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='main_member',
            field=models.BooleanField(default=True),
        ),
    ]
